import { ReconciledNode } from './FlowReconciler';

export class MarkdownDocGenerator {
    public static generate(nodes: ReconciledNode[]): string {
        let output = "# Living Documentation\n\n_Generated by CodePulse_\n\n";

        // Group by Class (Heuristic: Split name by dot)
        const methods = nodes.filter(n => n.type === 'method');

        output += "## Instrumented Methods\n";

        for (const node of methods) {
            if (!node.telemetry) continue; // Skip un-executed nodes for MVP or list them as "Untested"

            const statusIcon = node.telemetry.executionCount > 0 ? "✅" : "⚠️";

            output += `### ${statusIcon} ${node.name}\n`;
            output += `**Status:** ${node.telemetry.executionCount > 0 ? 'Verified in Production' : 'Not Detected'}\n`;
            output += `- **Executions:** ${node.telemetry.executionCount}\n`;
            output += `- **Avg Duration:** ${node.telemetry.avgDurationMs}ms\n`;
            output += `- **Last Verified:** ${node.telemetry.lastVerified}\n\n`;

            if (node.telemetry.discoveredDependencies.length > 0) {
                output += `#### 🔗 Runtime Dependencies\n`;
                node.telemetry.discoveredDependencies.forEach(dep => {
                    output += `- ${dep}\n`;
                });
                output += "\n";
            }

            output += `#### 🧜 Mermaid Flow\n`;
            output += "```mermaid\n";
            output += "graph TD;\n";
            output += `  ${node.id}[${node.name}]`;

            node.telemetry.discoveredDependencies.forEach((dep, index) => {
                const cleanDep = dep.replace(/[: ]/g, '_');
                output += ` -->|${dep.split(':')[0]}| dep${index}_${cleanDep}[${dep.substring(4)}];\n`;
                output += `  ${node.id} --> dep${index}_${cleanDep};\n`; // Redundant line fixed in logic?? No, just one link.
            });
            // Fix diagram logic above:
            // A --> B

            output += "```\n\n";
            output += "---\n\n";
        }

        return output;
    }
}
